{% set name = "testapp_conda_package" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/shatylo/testapp_conda_package.git

build:
  number: 0
  
requirements:
  build:
    - ninja
    - cmake

about:
  summary: TestApp for conda package